/**
 * Demo listing corpus for Propster.
 *
 * These are FICTIONAL listings written for the hackathon demo. Addresses are
 * generic, and every phone number is in a reserved demo block that does not
 * route to a real subscriber. Nothing here represents a real property, a real
 * agent or a real asking price.
 *
 * `demoScenario` drives the deterministic mock phone provider only. When a
 * real CALL-E key is configured, the live conversation is the only source of
 * verified facts and this field is ignored.
 */

export type DemoScenario =
  | "clean"
  | "price_mismatch"
  | "amenity_missing"
  | "unavailable"
  | "partial"
  | "no_answer";

export interface SeedProperty {
  title: string;
  description: string;
  location: string;
  area: string;
  propertyType: string;
  bedrooms: number;
  bathrooms: number;
  rent: number;
  rentPeriod: "monthly" | "yearly";
  amenities: string[];
  imageUrl: string;
  sourceUrl: string;
  agentName: string;
  agentPhone: string;
  listedAt: string;
  demoScenario: DemoScenario;
}

/** Reserved demo range. Not a routable subscriber block. */
const demoPhone = (n: number) => "+23470000000" + String(n).padStart(2, "0");

/**
 * The one listing that can be dialled for real, read from the environment.
 *
 * A live number must never be committed to the repository: this file is part of
 * a submission that gets read by strangers. Set DEMO_AGENT_PHONE in .env to the
 * number that should receive demo calls. Without it the listing falls back to
 * the fictional range and simply cannot be dialled, which is the safe default.
 */
const DEMO_AGENT_PHONE = process.env.DEMO_AGENT_PHONE?.trim() || demoPhone(1);

/**
 * Vendored asset path. Images live in `public/img/` and are regenerated by
 * `npm run vendor:images`; each name also has a `-sm` variant that property
 * cards use instead of downscaling the large file.
 */
const photo = (name: string) => "/img/" + name + ".webp";

export const SEED_PROPERTIES: SeedProperty[] = [
  // --- Lekki: the demo search hits these first -----------------------------
  {
    title: "3 Bedroom Apartment with BQ",
    description:
      "Spacious three bedroom flat in a serviced block off Admiralty Way. Fitted kitchen, all rooms en suite, dedicated parking bay and 24 hour estate security. Prepaid meter installed.",
    location: "Lekki Phase 1, Lagos",
    area: "Lekki Phase 1",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    rent: 7_500_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Generator", "Borehole", "Air conditioning"],
    imageUrl: photo("lekki-bq"),
    sourceUrl: "https://example.com/listings/lekki-phase-1-3bed-apartment",
    // The one listing wired to a real number for the live demo. Everything
    // else keeps a fictional number, and CALLE_PHONE_ALLOWLIST refuses to
    // dial anything but this, so a mis-click cannot ring a stranger.
    agentName: "Live demo contact",
    agentPhone: DEMO_AGENT_PHONE,
    listedAt: "2026-08-14",
    demoScenario: "clean",
  },
  {
    title: "3 Bedroom Flat, Chevron Drive",
    description:
      "Newly renovated three bedroom flat close to the Chevron roundabout. Open plan living, ample parking, estate generator and borehole water. Prepaid meter.",
    location: "Chevron, Lekki, Lagos",
    area: "Chevron",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    rent: 6_800_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Generator", "Borehole"],
    imageUrl: photo("chevron"),
    sourceUrl: "https://example.com/listings/chevron-3bed-flat",
    agentName: "Tunde Bakare (demo contact)",
    agentPhone: demoPhone(2),
    listedAt: "2026-08-21",
    demoScenario: "price_mismatch",
  },
  {
    title: "3 Bedroom Terrace, Ikate",
    description:
      "Well finished three bedroom terrace in a small gated close at Ikate Elegushi. Private parking for two cars, treated borehole water, prepaid electricity meter and full estate security.",
    location: "Ikate, Lekki, Lagos",
    area: "Ikate",
    propertyType: "terrace",
    bedrooms: 3,
    bathrooms: 4,
    rent: 7_800_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Borehole", "Generator"],
    imageUrl: photo("property-04"),
    sourceUrl: "https://example.com/listings/ikate-3bed-terrace",
    agentName: "Ngozi Eze (demo contact)",
    agentPhone: demoPhone(3),
    listedAt: "2026-08-09",
    demoScenario: "clean",
  },
  {
    title: "3 Bedroom Apartment, Lekki Phase 1 (Waterfront)",
    description:
      "Bright waterfront-facing three bedroom apartment. Fully serviced block with lift, gym, parking, prepaid meter and round the clock security.",
    location: "Lekki Phase 1, Lagos",
    area: "Lekki Phase 1",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    rent: 7_900_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Gym", "Elevator", "Generator"],
    imageUrl: photo("waterfront"),
    sourceUrl: "https://example.com/listings/lekki-waterfront-3bed",
    agentName: "Kelechi Nwosu (demo contact)",
    agentPhone: demoPhone(4),
    listedAt: "2026-07-30",
    demoScenario: "unavailable",
  },
  {
    title: "3 Bedroom Apartment, Agungi",
    description:
      "Three bedroom apartment in a quiet street at Agungi. Parking space, prepaid meter, borehole and gated compound with a security post.",
    location: "Agungi, Lekki, Lagos",
    area: "Agungi",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    rent: 5_500_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Borehole"],
    imageUrl: photo("agungi"),
    sourceUrl: "https://example.com/listings/agungi-3bed",
    agentName: "Ifeoma Balogun (demo contact)",
    agentPhone: demoPhone(5),
    listedAt: "2026-08-25",
    demoScenario: "partial",
  },
  {
    title: "3 Bedroom Apartment, Osapa London",
    description:
      "Three bedroom apartment in a family block at Osapa. Parking, generator, prepaid meter and estate security. Fibre internet available in the building.",
    location: "Osapa London, Lekki, Lagos",
    area: "Osapa London",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    rent: 7_200_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Generator", "Internet"],
    imageUrl: photo("osapa"),
    sourceUrl: "https://example.com/listings/osapa-3bed",
    agentName: "Segun Adeyemi (demo contact)",
    agentPhone: demoPhone(6),
    listedAt: "2026-08-18",
    demoScenario: "amenity_missing",
  },
  {
    title: "3 Bedroom Flat, Sangotedo",
    description:
      "Affordable three bedroom flat in a new estate at Sangotedo. Parking, borehole, prepaid meter and gatehouse security.",
    location: "Sangotedo, Ajah, Lagos",
    area: "Sangotedo",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    rent: 3_200_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Borehole"],
    imageUrl: photo("sangotedo"),
    sourceUrl: "https://example.com/listings/sangotedo-3bed",
    agentName: "Blessing Umoh (demo contact)",
    agentPhone: demoPhone(7),
    listedAt: "2026-08-27",
    demoScenario: "no_answer",
  },

  // --- Wider Lagos: shows the search is not hardcoded to one area ----------
  {
    title: "2 Bedroom Apartment, Ajah",
    description:
      "Compact two bedroom apartment near Abraham Adesanya. Parking, prepaid meter and estate security.",
    location: "Ajah, Lagos",
    area: "Ajah",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    rent: 2_400_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security"],
    imageUrl: photo("ajah"),
    sourceUrl: "https://example.com/listings/ajah-2bed",
    agentName: "Emeka Obi (demo contact)",
    agentPhone: demoPhone(8),
    listedAt: "2026-08-11",
    demoScenario: "clean",
  },
  {
    title: "4 Bedroom Semi-Detached Duplex, Ikoyi",
    description:
      "Four bedroom semi detached duplex with a boys quarters in a prime Ikoyi close. Pool, gym, lift, full facility management and dedicated parking.",
    location: "Ikoyi, Lagos",
    area: "Ikoyi",
    propertyType: "duplex",
    bedrooms: 4,
    bathrooms: 5,
    rent: 25_000_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Security", "Generator", "Swimming pool", "Gym", "Elevator", "Serviced"],
    imageUrl: photo("ikoyi"),
    sourceUrl: "https://example.com/listings/ikoyi-4bed-duplex",
    agentName: "Folake Martins (demo contact)",
    agentPhone: demoPhone(9),
    listedAt: "2026-07-22",
    demoScenario: "clean",
  },
  {
    title: "3 Bedroom Serviced Apartment, Victoria Island",
    description:
      "Fully serviced three bedroom apartment on Victoria Island. Service charge covers diesel, water, cleaning and security. Lift, gym and covered parking.",
    location: "Victoria Island, Lagos",
    area: "Victoria Island",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    rent: 15_000_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Security", "Generator", "Gym", "Elevator", "Serviced", "Internet"],
    imageUrl: photo("vi-serviced"),
    sourceUrl: "https://example.com/listings/vi-3bed-serviced",
    agentName: "Chidi Anyanwu (demo contact)",
    agentPhone: demoPhone(10),
    listedAt: "2026-08-05",
    demoScenario: "partial",
  },
  {
    title: "2 Bedroom Flat, Yaba",
    description:
      "Two bedroom flat walking distance from the Yaba tech cluster. Prepaid meter, borehole and secure compound. Fibre internet on the street.",
    location: "Yaba, Lagos",
    area: "Yaba",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    rent: 3_500_000,
    rentPeriod: "yearly",
    amenities: ["Prepaid meter", "Security", "Borehole", "Internet"],
    imageUrl: photo("yaba"),
    sourceUrl: "https://example.com/listings/yaba-2bed",
    agentName: "Yemi Coker (demo contact)",
    agentPhone: demoPhone(11),
    listedAt: "2026-08-23",
    demoScenario: "clean",
  },
  {
    title: "3 Bedroom Bungalow, Ikeja GRA",
    description:
      "Detached three bedroom bungalow in Ikeja GRA with a generous compound. Parking for three cars, borehole, generator house and prepaid meter.",
    location: "Ikeja GRA, Lagos",
    area: "Ikeja",
    propertyType: "bungalow",
    bedrooms: 3,
    bathrooms: 3,
    rent: 6_000_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Borehole", "Generator"],
    imageUrl: photo("ikeja"),
    sourceUrl: "https://example.com/listings/ikeja-gra-3bed-bungalow",
    agentName: "Bola Ogunleye (demo contact)",
    agentPhone: demoPhone(12),
    listedAt: "2026-08-16",
    demoScenario: "price_mismatch",
  },
  {
    title: "1 Bedroom Studio, Lekki Phase 1",
    description:
      "Modern studio apartment for a single professional. Prepaid meter, shared parking and estate security.",
    location: "Lekki Phase 1, Lagos",
    area: "Lekki Phase 1",
    propertyType: "studio",
    bedrooms: 1,
    bathrooms: 1,
    rent: 3_000_000,
    rentPeriod: "yearly",
    amenities: ["Prepaid meter", "Security", "Parking"],
    imageUrl: photo("waterfront"),
    sourceUrl: "https://example.com/listings/lekki-studio",
    agentName: "Amaka Nnadi (demo contact)",
    agentPhone: demoPhone(13),
    listedAt: "2026-08-29",
    demoScenario: "clean",
  },
  {
    title: "4 Bedroom Terrace, Lekki Phase 1",
    description:
      "Four bedroom terrace with a study and BQ. Estate generator, borehole, prepaid meter, parking for two and manned gate.",
    location: "Lekki Phase 1, Lagos",
    area: "Lekki Phase 1",
    propertyType: "terrace",
    bedrooms: 4,
    bathrooms: 5,
    rent: 12_000_000,
    rentPeriod: "yearly",
    amenities: ["Parking", "Prepaid meter", "Security", "Generator", "Borehole"],
    imageUrl: photo("property-04"),
    sourceUrl: "https://example.com/listings/lekki-4bed-terrace",
    agentName: "Uche Nwachukwu (demo contact)",
    agentPhone: demoPhone(14),
    listedAt: "2026-08-02",
    demoScenario: "clean",
  },
];
